; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = hub_esp32

[common]
baud_rate = 115200
build_flags = 
	-D SERIAL_BAUD=${common.baud_rate}
	-D RADIO_CHANNEL=100

[env:hub_esp32]
platform = espressif32
board = esp32dev
framework = arduino
upload_port = COM5
monitor_port = COM5
monitor_speed = ${common.baud_rate}
upload_speed = 921600
build_flags = 
	${common.build_flags}
	-D DEVICE_ROLE_HUB
	-D USE_WIFI
	-D USE_MQTT
	-D USE_DYNAMIC_LOGS
	-D RADIO_CE_PIN=12
	-D RADIO_CSN_PIN=5
	-D RADIO_SCK_PIN=18
	-D RADIO_MOSI_PIN=23
	-D RADIO_MISO_PIN=19
	-D RADIO_IRQ_PIN=32
lib_deps = 
	knolleary/PubSubClient @ ^2.8
	bblanchon/ArduinoJson @ ^7.3.0
	nrf24/RF24 @ ^1.5.0
	fastled/FastLED @ 3.7.0
	plerup/EspSoftwareSerial@^8.2.0

[env:remote_rf_nano]
platform = atmelavr
board = nanoatmega328new
framework = arduino
upload_port = COM3
monitor_port = COM3
monitor_speed = ${common.baud_rate}
build_flags = 
	${common.build_flags}
	-D DEVICE_ROLE_REMOTE
	-D HAS_LEDS
	-D USE_INTERNAL_RADIO
	-D RADIO_CE_PIN=10
	-D RADIO_CSN_PIN=9
	-D NUM_LEDS=50
lib_deps = 
	nrf24/RF24 @ ^1.5.0
	fastled/FastLED @ 3.7.0
	
[env:remote_nano]
platform = atmelavr
board = nanoatmega328
framework = arduino
upload_port = COM6
monitor_port = COM6
monitor_speed = 9600
build_flags = 
	-D SERIAL_BAUD=9600
	-D DEVICE_ROLE_REMOTE
	-D HAS_Si7021_SENSOR
	-D HAS_HLK_LK2420_SENSOR
	-D RADIO_DEBUG=1
	-D RADIO_CE_PIN=9
	-D RADIO_CSN_PIN=10
	-D RADIO_IRQ_PIN=2
	-D RADIO_CHANNEL=100
lib_deps = 
	nrf24/RF24 @ ^1.5.0
	fastled/FastLED @ 3.7.0
	adafruit/Adafruit Si7021 Library@^1.5.3
