; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = hub_esp32

[common]
baud_rate = 115200
build_flags = 
    -D SERIAL_BAUD=${common.baud_rate}

[env:hub_esp32]
platform = espressif32
board = esp32dev
framework = arduino
upload_port = COM3
monitor_port = COM3
monitor_speed = ${common.baud_rate}
upload_speed = 921600
build_flags = 
    ${common.build_flags}
    -D DEVICE_ROLE_HUB
    -D USE_WIFI
    -D USE_MQTT
    -D RADIO_CE_PIN=12
    -D RADIO_CSN_PIN=5
    -D RADIO_SCK_PIN=18
    -D RADIO_MOSI_PIN=23
    -D RADIO_MISO_PIN=19
    -D RADIO_IRQ_PIN=32
lib_deps = 
    knolleary/PubSubClient @ ^2.8
    bblanchon/ArduinoJson @ ^7.3.0
    nrf24/RF24 @ ^1.5.0
    fastled/FastLED @ 3.7.0 ; Pinned for stability

[env:remote_rf_nano]
platform = atmelavr
board = nanoatmega328new ; RF-Nano usually uses the new bootloader
framework = arduino
upload_port = COM5
monitor_port = COM5
monitor_speed = ${common.baud_rate}
build_flags = 
    ${common.build_flags}
    -D DEVICE_ROLE_REMOTE
    -D HAS_LEDS
    -D USE_INTERNAL_RADIO
    -D RADIO_CE_PIN=10
    -D RADIO_CSN_PIN=9
    -D NUM_LEDS=50
lib_deps = 
    nrf24/RF24 @ ^1.5.0
    fastled/FastLED @ 3.7.0